apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiapapod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiapapod
  template:
    metadata:
      labels:
        app: fiapapod
    spec:
      containers:
      - name: fiapapod
        image: brnmatos/fiapapi:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fiapapod-service
spec:
  selector:
    app: fiapapod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer